#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/merkletree
  
  autopep8 -ai -r merkletree merkleize *.py
  echo "not styling testData/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
