[meta]
version = "0.1.0"

[project]
name = "merkletree"
package = "merkletree"
main_lang = "py"
version = "5.3.10"
version_date = "2018-02-04"
author = "Jim Dixon"
author_email = "jdd@gmail.com"
description = "merkle tree library"
copyright = "2011-2017"
dev_status = "beta"
license = "mit"
relpath = "py/merkletree"
state = "shared"
url = "https://jddixon.github.io/merkletree"

[py]
packages = [ "merkletree",]
package_dir = [ "src",]
test_dir = "tests"
py_modules = []
scripts = [ "src/merkleize",]
ext_modules = []
distshare = [ "optionz", "rnglib", "xlattice_py",]
requirements = [ "setuptools", "pysha3",]
test_requirements = []
